In [17]:
from mcnpy.cov.parse_covmat import read_scale_covmat, read_njoy_covmat

In [18]:
scale_file_path = 'files/scale.rev05.44groupcov.txt'

In [19]:
covmat = read_scale_covmat(scale_file_path)

In [20]:
covmat

                            Covariance Matrix Information                            

This object contains covariance matrix data from nuclear data files (SCALE, NJOY, etc).
Each matrix represents the covariance between cross sections for specific
isotope-reaction pairs across energy groups.

Covariance type: SCALE

Covariance Data Summary:
-------------------------------------------------------------------------------------
Property                            Value                                          
-------------------------------------------------------------------------------------
Number of Energy Groups             44                                             
Number of Covariance Matrices       2235                                           
Number of Unique Isotopes           407                                            
Number of Unique Reactions          12                                             
----------------------------------------------------------------

In [64]:
import numpy as np

N, M = 44, 2
A = np.random.rand(M*N, M*N)   # tu array 88×88
type(A)
print(A.shape)

(88, 88)


In [61]:
for i in range(M):
    for j in range(M):
        # extraemos el bloque (i,j) de 44×44
        bloque = A[i*N:(i+1)*N, j*N:(j+1)*N]
        # lo invertimos en filas y columnas
        A[i*N:(i+1)*N, j*N:(j+1)*N] = np.flip(bloque, axis=(0,1))


In [62]:
A

array([[0.46201779, 0.13451014, 0.47565128, ..., 0.92180371, 0.87449215,
        0.92865356],
       [0.64238742, 0.17590254, 0.79176596, ..., 0.5656249 , 0.88572352,
        0.88288611],
       [0.19817339, 0.2088591 , 0.03503219, ..., 0.63490914, 0.55534139,
        0.88252606],
       ...,
       [0.1170278 , 0.18272039, 0.59617616, ..., 0.54001246, 0.1816188 ,
        0.06890118],
       [0.73907631, 0.59034392, 0.57176381, ..., 0.57901548, 0.16861412,
        0.54195662],
       [0.73164108, 0.55832833, 0.61320385, ..., 0.73365819, 0.44522812,
        0.32013073]], shape=(88, 88))

In [32]:
df = covmat.to_dataframe()
df

ISO_H  REAC_H    ISO_V  REAC_V  \
0           0       0        0       0   
1     8001001       2  8001001       2   
2     8001001     102  8001001     102   
3     8001002       2  8001002       2   
4     8001002     102  8001002     102   
...       ...     ...      ...     ...   
2231    22048       2    22048       4   
2232    22048       2    22048      16   
2233    22048       2    22048     102   
2234    22048       2    22048     103   
2235    22048       2    22048     107   

                                                    STD  
0     [1e-11, 3e-09, 7.5e-09, 1e-08, 2.53e-08, 3e-08...  
1     [[1e-06, 1e-06, 1e-06, 1e-06, 1e-06, 1e-06, 1e...  
2     [[2.4999999e-05, 2.4999999e-05, 2.4999999e-05,...  
3     [[0.00039999999, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
4     [[0.00089999998, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
...                                                 ...  
2231  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
2232  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
2233  [[-3.794489e-05, -4.2001837e-05, -4.2837644e-0...  
2234  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
2235  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  

[2236 rows x 5 columns]

In [38]:
h1df = df[df['ISO_H'] == 1001]

In [46]:
for i in h1df[h1df['REAC_H'] == 102]['STD']:
    print(i)


[[2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.6218e-05, 3.8570001e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.4999999e-05, 2.6218e-05, 3.8570001e-06, 0.0, 0.

In [58]:
h1df[h1df['REAC_H'] == 102]['STD']

2182    [[2.4999999e-05, 2.4999999e-05, 2.4999999e-05,...
Name: STD, dtype: object

In [29]:
covmat.get_isotope_covariance_matrix(1001, [2,102])

array([[1.0000000e-06, 1.0000000e-06, 1.0000000e-06, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e-06, 1.0000000e-06, 1.0000000e-06, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e-06, 1.0000000e-06, 1.0000000e-06, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.3769000e-01,
        1.1413000e-01, 6.5334000e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.1413000e-01,
        9.4628997e-02, 5.4271001e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 6.5334000e-02,
        5.4271001e-02, 3.1564001e-02]], shape=(88, 88))

In [6]:
import numpy as np

combined_cov = covmat.get_isotope_covariance_matrix(1001, [2, 102])
combined_cov

# write the covariance matrix to a txt file with space delimiter and .18e format
with open('scale_covmat_des.txt', 'w') as f:
    np.savetxt(f, combined_cov.T, fmt='%.18e', delimiter=' ')

In [8]:
df = covmat.get_reactions_summary()
df

Isotope                   Reactions
0       1001                    [2, 102]
1       1002                [2, 16, 102]
2       1003                     [2, 16]
3       2003          [2, 102, 103, 104]
4       2004                         [2]
..       ...                         ...
402  3006000  [2, 4, 102, 103, 104, 107]
403  7001001                    [2, 102]
404  8001001                    [2, 102]
405  8001002                [2, 16, 102]
406  9001001                    [2, 102]

[407 rows x 2 columns]

In [9]:
df[df['Isotope'] == 92235]

Isotope                       Reactions
344    92235  [2, 4, 16, 18, 102, 452, 1018]

In [10]:
covmat.get_isotope_covariance_matrix(26056, [2,4,102,103,107])

array([[0.002475, 0.002475, 0.002475, ..., 0.      , 0.      , 0.      ],
       [0.002475, 0.002475, 0.002475, ..., 0.      , 0.      , 0.      ],
       [0.002475, 0.002475, 0.002475, ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.033708, 0.025971, 0.020686],
       [0.      , 0.      , 0.      , ..., 0.025971, 0.035624, 0.020723],
       [0.      , 0.      , 0.      , ..., 0.020686, 0.020723, 0.024208]],
      shape=(220, 220))

In [11]:
cov34_file_path = '/home/MONLEON-JUAN/MCNPy/mcnpy/cov/files/260560_80.06.xs.gendf'

In [12]:
covmat = read_njoy_covmat(cov34_file_path)

In [13]:
covmat

                            Covariance Matrix Information                            

This object contains covariance matrix data from nuclear data files (SCALE, NJOY, etc).
Each matrix represents the covariance between cross sections for specific
isotope-reaction pairs across energy groups.

Covariance type: NJOY

Covariance Data Summary:
-------------------------------------------------------------------------------------
Property                            Value                                          
-------------------------------------------------------------------------------------
Number of Energy Groups             56                                             
Number of Covariance Matrices       7                                              
Number of Unique Isotopes           1                                              
Number of Unique Reactions          7                                              
-----------------------------------------------------------------

In [14]:
df = covmat.to_dataframe()
df

ISO_H  REAC_H  ISO_V  REAC_V  \
0      0       0      0       0   
1   2631       1   2631       1   
2   2631       2   2631       2   
3   2631       4   2631       4   
4   2631       5   2631       5   
5   2631      16   2631      16   
6   2631     102   2631     102   
7   2631     103   2631     103   

                                                 STD  
0  [1e-05, 0.004, 0.01, 0.0253, 0.04, 0.05, 0.06,...  
1  [[0.0004761941, 0.0003555683, 0.0002816217, 0....  
2  [[9.578469e-05, 0.0001100216, 0.0001122962, 0....  
3  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
4  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
5  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...  
6  [[0.002362302, 0.002362308, 0.002362332, 0.002...  
7  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...

In [15]:
len(covmat.energy_grid)

57

In [14]:
len(df['STD'][0])

57